Repository roc-lang/roc, pull requests merged in 2022-11, with the labels that each got.

#4124 WIP windows: build tests, run some tests
  .github/workflows/windows.yml
  crates/compiler/builtins/build.rs
Labels: ci/cd, windows

#4457 Compare benches of branch with main
  .github/workflows/benchmarks.yml
Labels: ci/cd

#4455 patch windows lld-link error
  .github/workflows/windows.yml
Labels: ci/cd, windows

#4480 check links key was defined twice
  .github/workflows/markdown_link_check.yml
Labels: ci/cd

#4500 add missing includes for clang 14
  examples/parser/platform/host.c
  examples/platform-switching/c-platform/host.c
  examples/ruby-interop/platform/host.c
Labels: ci/cd, macos

#3311 macOS x86_64 test workflow
  .github/workflows/nix_macos_x86_64.yml
Labels: public

#4518 add zig version to homebrew commands
  BUILDING_FROM_SOURCE.md
  getting_started/macos_apple_silicon.md
  getting_started/macos_x86_64.md
Labels: repo docs

#4531 improve guide on how to sign unsigned commits
  CONTRIBUTING.md
Labels: repo docs

#4549 improve/expand design docs for editor and plugins
  design/editor/design.md
  design/editor/editor-ideas.md
  design/editor/plugins/api.md
  design/editor/plugins/inspiration.md
  design/editor/plugins/plugin_use_cases.md
  design/editor/plugins/security.md
  design/editor/plugins/ui_research.md
  design/language/Abilities.md
Labels: editor

#4570 do spellcheck on github servers
  .github/workflows/spellcheck.yml
Labels: ci/cd

#4571 added editor goals and reqs docs
  design/editor/goals.md
  design/editor/requirements.md
Labels: repo docs

#4601 design doc updates
  design/editor/design.md
  design/editor/goals.md
  design/editor/requirements.md
Labels: repo docs

#4598 Add `dbg` section to tutorial
  www/public/site.css
  www/public/tutorial/index.html
Labels: blocked

#4637 check the exit status of the link cmd
  crates/compiler/build/src/link.rs
Labels: linking
